language: node_js
cache:
  directories:
    - '~/.npm'
node_js:
  - lts/*
script: npm run build
deploy:
  provider: npm
  email: berkeleybross@gmail.com
    api_key:
    secure: UXDWGJRGCHlU6CJ88ag4mK5QKNfa6AyEwJ2FXw1t36lWVoH825Nt5ib1nK/XTP4yuEtgmsRqh5M9loZWErhfTQEg5gbOiDU8krxCVK2Q94M5Ct/kzyv0Ua8hc/dlRLClnVBJvvHb0MZlz5A/yk9iNMOSCQNW3AkcsxnRDmqnNFWE1P8qk81ly/Cb8HXgAuNl4/ZFI8BVJNZXC5MCgraHP/nt9sXawBcFfMksL4IJpoZcOVVfJ5duq1piSSM82R8T9kaFwbCKhAYarl3qRkR8Wc4L2H5IJJe1dNr1T1PSo5EZRrSWzaVExF/OffrLZOC5e2RdeDBJ10exhXbnNANVQCmvLE2+9iXlJBozWXqssW0uN9S1O6fPP0cYUHOpKM77et6Wzg2rn6YKInBJSI5+89nDCznZ4qVVPFQvW96QDOuOkG/MCVc4qiqluC3wZTOgXtXcnPMxTUyAEX6PgmlpGZeWHWe5jIAAO1oeL7yZ7UHYe2D4Twine4yqQ6y0nolXrNuf1J0EXz0A3BdlVScHXlq/dDjczqK9ADe0d1xN85K7OOVVVfsga4gtG1MgYXI32DVQ/bxjrNuTBfj0GTG0vM0nFDY/NUG6e5MEqkt5BzVbhtxHKXfujt97RnDQmax3BOUSUiHgGfWkX82vJNZdXhQdMs+O9oxsw0dlBHJlJYA=
  on:
    tags: true
    branch: master
    repo: berkeleybross/qe
  skip_cleanup: true # Need dist folder
