language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - lts/*
script: npm run build
deploy:
  provider: npm
  email: berkeleybross@gmail.com
  api_key:
    secure: 'H2hAFH1GYzivpPsOaoNkaxxX2vjN+SnQgIhckJ2J43lPeTirwBY8XyRlNAXYQUhOjyMQ5EmGge/mwRw5O65osloRuxpsvKcjS1WNh8a5qxCeebVne5A3tgcQt26Loi5mJHGZri2I4L11VBtLS7g7wCalGhCbIdgloB+Um9btsbn/V8ducyi9h0Q5JxWdaLKp2BGmVBe5Eril3EW8UakA2Wyci5Mq6VAPThGaJFFPowK/EYqxhv97EXat4nxKA4OaoUDh9uc5Sh6hjDxpCHGYpcxEqEjvugkQeQhncQZ70n/0iGcTSAOtEMnQiI/oprInfcE38OJiAEseS9ICHyPTe6f4qkcsEt16ZvANIUgiDVOfYYkvB+twfNNIofuhqcQnRqf8jbrn7saDsqOX/K22lDX85dJpXA103D5rJJsrxkMYyWEFNc1pzqatJxO5lvLkPhnnFyTfhrcyE0JyZG/FLLeTPwfLVnJs4mKU1jKg8kpJe7GbzROYFLiiKJktVcQEYPwDDdhL4oXxPt/anrJ6kFsSskFYt81BlWJ8E2pDQyerGMrBJ7bmb0QEopXf+3KPjM8GV08hbQQ8sVStwwwY2Y1gAabXdCg5WNKK4qzZiA2Dg6m7vBRDeVXjiAkHFioSGGWT38Yr24aCcsRz0yvzlscb9+kSBqGqFYqy8/2nTlI='
  on:
    tags: true
    branch: master
    repo: berkeleybross/qe
  skip_cleanup: true # Need dist folder
